#pragma checksum "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "28B1EC6B6AF0F15E62B931BD75B9C4FEC2A14105"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace LibraryManagement.Views.Auth {
    
    
    /// <summary>
    /// RegisterView
    /// </summary>
    public partial class RegisterView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 164 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtFullName;
        
        #line default
        #line hidden
        
        
        #line 177 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtEmail;
        
        #line default
        #line hidden
        
        
        #line 191 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox TxtRegPassword;
        
        #line default
        #line hidden
        
        
        #line 194 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PlaceholderPassword;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnRegister;
        
        #line default
        #line hidden
        
        
        #line 214 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BtnGoToSignIn;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StatusCard;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtStatus;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/LibraryManagement;component/views/auth/registerview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtFullName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.TxtEmail = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.TxtRegPassword = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 192 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
            this.TxtRegPassword.PasswordChanged += new System.Windows.RoutedEventHandler(this.TxtRegPassword_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.PlaceholderPassword = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.BtnRegister = ((System.Windows.Controls.Button)(target));
            
            #line 208 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
            this.BtnRegister.Click += new System.Windows.RoutedEventHandler(this.BtnRegister_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.BtnGoToSignIn = ((System.Windows.Controls.Button)(target));
            
            #line 215 "..\..\..\LibraryManagement\Views\Auth\RegisterView.xaml"
            this.BtnGoToSignIn.Click += new System.Windows.RoutedEventHandler(this.BtnGoToSignIn_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.StatusCard = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.TxtStatus = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

