#pragma checksum "..\..\LibraryManagement\Views\AuthWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0EAF5A132EE1BBA8A27B74FC524B4267D8C17575"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LibraryManagement.ViewModels;
using LibraryManagement.Views.Auth;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace LibraryManagement.Views {
    
    
    /// <summary>
    /// AuthWindow
    /// </summary>
    public partial class AuthWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 14 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal LibraryManagement.ViewModels.AuthViewModel ViewModel;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border CardBorder;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid CardContainer;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PanelSignIn;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform TransSignIn;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal LibraryManagement.Views.Auth.LoginView LoginControl;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PanelRegister;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform TransRegister;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal LibraryManagement.Views.Auth.RegisterView RegisterControl;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid SlidingDarkOverlay;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform TransOverlay;
        
        #line default
        #line hidden
        
        
        #line 150 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PanelWelcomeBack;
        
        #line default
        #line hidden
        
        
        #line 157 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform TransWelcomeBack;
        
        #line default
        #line hidden
        
        
        #line 188 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PanelStartPage;
        
        #line default
        #line hidden
        
        
        #line 195 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform TransStartPage;
        
        #line default
        #line hidden
        
        
        #line 236 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TabSignIn;
        
        #line default
        #line hidden
        
        
        #line 247 "..\..\LibraryManagement\Views\AuthWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TabRegister;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/LibraryManagement;component/views/authwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ViewModel = ((LibraryManagement.ViewModels.AuthViewModel)(target));
            return;
            case 2:
            this.CardBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.CardContainer = ((System.Windows.Controls.Grid)(target));
            
            #line 36 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            this.CardContainer.PreviewMouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.CardContainer_PreviewMouseLeftButtonDown);
            
            #line default
            #line hidden
            
            #line 37 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            this.CardContainer.PreviewMouseLeftButtonUp += new System.Windows.Input.MouseButtonEventHandler(this.CardContainer_PreviewMouseLeftButtonUp);
            
            #line default
            #line hidden
            return;
            case 4:
            this.PanelSignIn = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this.TransSignIn = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 6:
            this.LoginControl = ((LibraryManagement.Views.Auth.LoginView)(target));
            return;
            case 7:
            this.PanelRegister = ((System.Windows.Controls.Grid)(target));
            return;
            case 8:
            this.TransRegister = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 9:
            this.RegisterControl = ((LibraryManagement.Views.Auth.RegisterView)(target));
            return;
            case 10:
            this.SlidingDarkOverlay = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.TransOverlay = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 12:
            this.PanelWelcomeBack = ((System.Windows.Controls.Grid)(target));
            return;
            case 13:
            this.TransWelcomeBack = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 14:
            this.PanelStartPage = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.TransStartPage = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 16:
            
            #line 231 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            ((System.Windows.Controls.Grid)(target)).MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.TitleBar_MouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 17:
            this.TabSignIn = ((System.Windows.Controls.Button)(target));
            
            #line 236 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            this.TabSignIn.Click += new System.Windows.RoutedEventHandler(this.TabSignIn_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.TabRegister = ((System.Windows.Controls.Button)(target));
            
            #line 247 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            this.TabRegister.Click += new System.Windows.RoutedEventHandler(this.TabRegister_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            
            #line 263 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnMinimize_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            
            #line 285 "..\..\LibraryManagement\Views\AuthWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnClose_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

