#pragma checksum "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6A04052FA61CFE878113F3A476080D8B8A2BD4EB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace LibraryManagement.Views.Accounts {
    
    
    /// <summary>
    /// CreateAccountDialog
    /// </summary>
    public partial class CreateAccountDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 54 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtFullName;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtUsername;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CmbRole;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtEmail;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox TxtPassword;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox TxtConfirmPassword;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ErrorPanel;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtError;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/LibraryManagement;component/views/accounts/createaccountdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 7 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            ((LibraryManagement.Views.Accounts.CreateAccountDialog)(target)).Loaded += new System.Windows.RoutedEventHandler(this.Window_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TxtFullName = ((System.Windows.Controls.TextBox)(target));
            
            #line 56 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            this.TxtFullName.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.InputChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TxtUsername = ((System.Windows.Controls.TextBox)(target));
            
            #line 68 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            this.TxtUsername.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.InputChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CmbRole = ((System.Windows.Controls.ComboBox)(target));
            
            #line 74 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            this.CmbRole.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.InputChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.TxtEmail = ((System.Windows.Controls.TextBox)(target));
            
            #line 84 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            this.TxtEmail.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.InputChanged);
            
            #line default
            #line hidden
            return;
            case 6:
            this.TxtPassword = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 88 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            this.TxtPassword.PasswordChanged += new System.Windows.RoutedEventHandler(this.InputChanged);
            
            #line default
            #line hidden
            return;
            case 7:
            this.TxtConfirmPassword = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 94 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            this.TxtConfirmPassword.PasswordChanged += new System.Windows.RoutedEventHandler(this.InputChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.ErrorPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 9:
            this.TxtError = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            
            #line 113 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCancel_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            
            #line 115 "..\..\..\LibraryManagement\Views\Accounts\CreateAccountDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnCreate_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

