#pragma checksum "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9D30638A31B8EB6BBA41D936C518EEBA298F104C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LibraryManagement.ViewModels;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace LibraryManagement.Views.Accounts {
    
    
    /// <summary>
    /// MyAccountView
    /// </summary>
    public partial class MyAccountView : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 18 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton TabBtnProject;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton TabBtnProfile;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton TabBtnPassword;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelProject;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelProfile;
        
        #line default
        #line hidden
        
        
        #line 235 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ProfileAlertBox;
        
        #line default
        #line hidden
        
        
        #line 236 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtProfileAlert;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelPassword;
        
        #line default
        #line hidden
        
        
        #line 266 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdCurrent;
        
        #line default
        #line hidden
        
        
        #line 270 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdNew;
        
        #line default
        #line hidden
        
        
        #line 274 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PwdConfirm;
        
        #line default
        #line hidden
        
        
        #line 277 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PasswordAlertBox;
        
        #line default
        #line hidden
        
        
        #line 278 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock TxtPasswordAlert;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/LibraryManagement;component/views/accounts/myaccountview.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TabBtnProject = ((System.Windows.Controls.RadioButton)(target));
            
            #line 19 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            this.TabBtnProject.Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 2:
            this.TabBtnProfile = ((System.Windows.Controls.RadioButton)(target));
            
            #line 25 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            this.TabBtnProfile.Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TabBtnPassword = ((System.Windows.Controls.RadioButton)(target));
            
            #line 31 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            this.TabBtnPassword.Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 4:
            this.PanelProject = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 5:
            this.PanelProfile = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.ProfileAlertBox = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.TxtProfileAlert = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.PanelPassword = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 9:
            this.PwdCurrent = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 266 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            this.PwdCurrent.PasswordChanged += new System.Windows.RoutedEventHandler(this.PwdBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.PwdNew = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 270 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            this.PwdNew.PasswordChanged += new System.Windows.RoutedEventHandler(this.PwdBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.PwdConfirm = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 274 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            this.PwdConfirm.PasswordChanged += new System.Windows.RoutedEventHandler(this.PwdBox_PasswordChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.PasswordAlertBox = ((System.Windows.Controls.Border)(target));
            return;
            case 13:
            this.TxtPasswordAlert = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            
            #line 283 "..\..\..\LibraryManagement\Views\Accounts\MyAccountView.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BtnChangePassword_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

